
# For technical reasons, this file is *NOT* reloaded automatically
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Блог Бурухиной Ларисы Александровны
email: buruhina.larisa@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Рукоделие, педагогика, воспитание, дети, творчество
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://buruhina.github.io" # the base hostname & protocol for your site, e.g. http://example.com

paginate: 10

collections:
  category:
    output: true
    permalink: /category/:name

excerpt_separator: <!--more-->

prose:
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Выбрать категорию"
          placeholder: "категория"
          options:
            - name: "Будем красивыми"
              value: "Будем красивыми"
            - name: "Будем здоровыми"
              value: "Будем здоровыми"

ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes

# Build settings
theme: minima
  
# Exclude from processing.
exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
