
# For technical reasons, this file is *NOT* reloaded automatically
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Блог Бурухиной Ларисы Александровны
email: buruhina.larisa@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Рукоделие, педагогика, воспитание, дети, творчество
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://buruhina.github.io" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  category:
    output: true
    permalink: /category/:name

excerpt_separator: <!--more-->

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-admin
  - jekyll-gist
  - jekyll-paginate-v2
  
# Exclude from processing.
exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/

pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 10

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: '' 

  trail: 
    before: 1
    after: 1

  extension: html
  indexpage: 'index'
